### ISSUE TITLE
InvalidStateError

### ISSUE THREAD

**Issue by aliparlar** [one-signal/OneSignal-Website-SDK#22] opened 2016-02-27 13:55 UTC
(unknown): InvalidStateError
File https://cdn.onesignal.com/sdks/OneSignalSDK.js line 8 in [anonymous]
InvalidStateError Firefox 44.0	Windows 8.1 

Hello, I am occasionally getting these errors reported to my rollbar tracker.

**Comment by jasonpang** [comment] 2016-03-02 05:41
Hi,

Could you check if you're running in Private Browsing Mode / this setting: http://stackoverflow.com/a/15606077?

**Comment by jasonpang** [comment] 2016-03-04 23:56
Hi,

This error most likely has to do with not being able to open the browser's IndexedDB, which is like another kind of local storage.

In Firefox, this error occurs in Private Browsing mode or if the user has opted to not accept third-party cookies. In both of these cases, Firefox has decided that IndexedDB should not be accessible; in Chrome IndexedDB is accessible but I'm guessing the contents are cleared the moment Chrome's Incognito window is closed.

In our normal testing while developing the SDK we haven't come across this error except in rare cases where clearing data, subscribing to notifications, and re-clearing data in a very convoluted way sometimes triggers these errors in Firefox and Safari where IndexedDB is no longer accessible until all open tabs to the same origin are closed. It's unlikely your users are running into this case though.

Until we're able to gather more data on the issue, my best current guess is that users are accessing your site in Private Browsing mode on Firefox. Please update us if this error seems to occur more frequently than would be reasonable or if you have new data on the issue!

**Comment by aliparlar** [comment] 2016-03-05 00:06
Thanks for the info, I still see it regularly on my console every hour
since we are in active development.  I am not running private mode, I can't
think of any special settings except that I have an add blocker.

Did I send you a screen shot before?  I am attaching one now..   By the
way, there is no problem with subscription functionality.


Here is the page if you wish to look deeper

http://sb.idserv.com

It may occasionally be down and full of other errors.



On Sat, Mar 5, 2016 at 1:56 AM, Jason Pang <notifications@github.com> wrote:

> Hi,
>
> This error most likely has to do with not being able to open the browser's
> IndexedDB, which is like another kind of local storage.
>
> In Firefox, this error occurs in Private Browsing mode or if the user has
> opted to not accept third-party cookies. In both of these cases, Firefox
> has decided that IndexedDB should not be accessible; in Chrome IndexedDB is
> accessible but I'm guessing the contents are cleared the moment Chrome's
> Incognito window is closed.
>
> In our normal testing while developing the SDK we haven't come across this
> error except in rare cases where clearing data, subscribing to
> notifications, and re-clearing data in a very convoluted way sometimes
> triggers these errors in Firefox and Safari where IndexedDB is no longer
> accessible until all open tabs to the same origin are closed. It's unlikely
> your users are running into this case though.
>
> Until we're able to gather more data on the issue, my best current guess
> is that users are accessing your site in Private Browsing mode on Firefox.
> Please update us if this error seems to occur more frequently than would be
> reasonable or if you have new data on the issue!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/one-signal/OneSignal-Website-SDK/issues/22#issuecomment-192528356>
> .
>



-- 
Ali Parlar

**Comment by jasonpang** [comment] 2016-03-05 03:18
Thanks for the link! I wasn't able to reproduce the error; do you know of any steps that might reproduce this error?

Do you see the error on the browser's developer tools console while you're testing, or do you only discover the errors later on Rollbar? If you see it on your browser's console, do you think you could upload a screenshot? (couldn't see your attachment in your last post).

**Comment by aliparlar** [comment] 2016-03-05 12:40
Its always in the browser console, I don't see it in rollbar.

I am embedding the screenshot inside the email can you see it now?  I can
upload it to somewhere if you cant..

[image: Inline image 1]

On Sat, Mar 5, 2016 at 5:18 AM, Jason Pang <notifications@github.com> wrote:

> Thanks for the link! I wasn't able to reproduce the error; do you know of
> any steps that might reproduce this error?
>
> Do you see the error on the browser's developer tools console while you're
> testing, or do you only discover the errors later on Rollbar? If you see it
> on your browser's console, do you think you could upload a screenshot?
> (couldn't see your attachment in your last post).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/one-signal/OneSignal-Website-SDK/issues/22#issuecomment-192558284>
> .
>



-- 
Ali Parlar

**Comment by jasonpang** [comment] 2016-03-08 00:17
Hey aliparlar,

Could you upload the image somewhere? I can't see the image either on GitHub issues or in the email version of this thread.

**Comment by aliparlar** [comment] 2016-03-08 00:50
Hello sure,

Just FYI, I have not had much time to look into it either so there may also
be something wrong on my side.

https://www.dropbox.com/s/gav2vsedjfedz1q/k.png?dl=0

Happens on Version 48.0.2564.116 (64-bit)

var OneSignal = OneSignal || [];
OneSignal.LOGGING = true;
OneSignal.push(["init", {
appId: "505ea243-bb53-408a-9d0c-257a807e9c45",
subdomainName: 'kapisle'





On Tue, Mar 8, 2016 at 2:17 AM, Jason Pang


<notifications@github.com> wrote:

> Hey aliparlar,
>
> Could you upload the image somewhere? I can't see the image either on
> GitHub issues or in the email version of this thread.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/one-signal/OneSignal-Website-SDK/issues/22#issuecomment-193521468>
> .
>



-- 
Ali Parlar

**Comment by jasonpang** [comment] 2016-03-08 03:24
Oh, this seems to be a different error? I thought this was the InvalidStateError.

About the error you're getting, we actually fixed that today: https://github.com/one-signal/OneSignal-Website-SDK/pull/29

**Comment by aliparlar** [comment] 2016-03-08 11:44
Hello,

Sorry, I didnt notice the error has changed, I used to get the invalid
state error before. Thanks, I'll get the new version...

On Tue, Mar 8, 2016 at 5:24 AM, Jason Pang <notifications@github.com> wrote:

> Oh, this seems to be a different error? I thought this was the
> InvalidStateError.
>
> About the error you're getting, we actually fixed that today: #29
> <https://github.com/one-signal/OneSignal-Website-SDK/pull/29>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/one-signal/OneSignal-Website-SDK/issues/22#issuecomment-193584143>
> .
>



-- 
Ali Parlar

**Comment by jasonpang** [comment] 2016-03-08 19:20
Hey Aliparlar,

There's no need to get the new version as our SDK will be updating automatically for all users. The fix hasn't been deployed yet, but it will be deployed very soon.

How is the invalid state error looking like recently?

**Comment by aliparlar** [comment] 2016-03-08 20:00
I havent noticed it recently, I'll let you know if it surfaces again.. If I
am not mistaken, it was a very similar error complaining about "allowed
origins" but the error title was Invalid State...  fuzzy..  I will let you
know if I catch a solid bug

On Tue, Mar 8, 2016 at 9:20 PM, Jason Pang <notifications@github.com> wrote:

> Hey Aliparlar,
>
> There's no need to get the new version as our SDK will be updating
> automatically for all users. The fix hasn't been deployed yet, but it will
> be deployed very soon.
>
> How is the invalid state error looking like recently?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/one-signal/OneSignal-Website-SDK/issues/22#issuecomment-193928410>
> .
>



-- 
Ali Parlar

**Comment by jasonpang** [comment] 2016-03-09 00:51
Hey aliparlar,

I'm going to close this issue, but please feel free to open another if you get any other errors!

**Closed by jasonpang** 2016-03-09 00:51 UTC
